### ISSUE TITLE
Add support for modifiers

### ISSUE THREAD

**Issue by Samueru-sama** [X11Libre/xserver#1245]
### Describe the feature

fix for https://gitlab.freedesktop.org/mesa/mesa/-/issues/10093

### It should be implemented because

Allows using zink driver without needing to set `LIBGL_KOPPER_DRI2=1`

### Additional context

I have no idea why mesa did this nor what it does exactly. 

### Extra fields

- [x] I have checked the existing [issues](https://github.com/X11Libre/xserver/issues)
- [x] I have read the [Contributing Guidelines](https://github.com/X11Libre/xserver/blob/master/CONTRIBUTING.md)
- [ ] I'd like to work on this issue

**Comment by callmetango** [comment]
Thank you for reporting the issue! Could you please add a little more context to make this issue more consistent and standalone? I mean, without having to open the freedesktop.org Gitlab issue.

**Comment by Samueru-sama** [comment]
> Thank you for reporting the issue! Could you please add a little more context to make this issue more consistent and standalone? I mean, without having to open the freedesktop.org Gitlab issue.

Done, I don't know how much can be added since it boils down to having to set `LIBGL_KOPPER_DRI2=1` to use the zink driver.

**Comment by notbabaisyou** [comment]
The reason it doesn't work is that the Xorg DDX you are using doesn't implement the later extensions for DRI3 which is needed for Zink to use DRI3 directly.

Using `modesetting` should fix this as it implements them and is the intended DDX for Zink on X11.

**Comment by Samueru-sama** [comment]
> The reason it doesn't work is that the Xorg DDX you are using doesn't implement the later extensions for DRI3 which is needed for Zink to use DRI3 directly.
> 
> Using `modesetting` should fix this as it implements them and is the intended DDX for Zink on X11.

I see, well that's a shame, I use the amdgpu driver with TearFree since I use fastcompmgr as my compositor.

**Comment by Samueru-sama** [comment]
Update: Back when I made my previous comment I didn't know the modesetting driver had TearFree, I later moved to it when I discovered it had it which lead to this issue https://github.com/X11Libre/xserver/issues/1816

---

cc @josephcrowell 

https://github.com/X11Libre/xserver/issues/1816#issuecomment-3963598227

I just installed `xlibre-video-amdgpu 25.1.1-1` but I still cannot use zink unless I set `LIBGL_KOPPER_DRI2=1`

<img width="806" height="549" alt="Image" src="https://github.com/user-attachments/assets/e6874197-b2c9-492c-8c1a-64a2a58f4a31" />

**Comment by josephcrowell** [comment]
> I just installed `xlibre-video-amdgpu 25.1.1-1` but I still cannot use zink unless I set `LIBGL_KOPPER_DRI2=1`

I'll look in to it this afternoon.

**Comment by josephcrowell** [comment]
It looks like the level of DRI3 (or whether it has DRI3 at all) isn't being detected properly. I'm working through it right now.
